services:
  postegres:
    image: postgres:16
    container_name : bankapi_postegres
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpassword
      POSTGRES_DB: bankdb
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: