"""rename isActive to is_active

Revision ID: 0611e848afea
Revises: a08554c69bd2
Create Date: 2026-07-15 23:24:39.654942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0611e848afea'
down_revision: Union[str, Sequence[str], None] = 'a08554c69bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'isActive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
